/**
 * ChinguiSoft SMS Validation API — provider adapter.
 *
 * ┌──────────────────────────────────────────────────────────────────────────┐
 * │  This is the single source of truth for the ChinguiSoft API contract.   │
 * │  Change only this file if the provider contract changes.                 │
 * └──────────────────────────────────────────────────────────────────────────┘
 *
 * Real API contract (confirmed):
 *   Method  : POST
 *   URL     : {BASE_URL}/api/sms/validation/{VALIDATION_KEY}
 *   Headers : Validation-token: {VALIDATION_TOKEN}
 *             Content-Type: application/json
 *   Body    : { "phone": "XXXXXXXX", "lang": "fr"|"ar", "code": "XXXXXX" }
 *
 * Notes:
 *   - VALIDATION_KEY  → part of the URL path (not a header, not a body field)
 *   - VALIDATION_TOKEN → in the "Validation-token" header (exact capitalisation)
 *   - phone           → local Mauritanian format WITHOUT the +222 prefix
 *                        e.g. +22249141433 → 49141433
 *   - lang            → "fr" for French, "ar" for Arabic
 *   - code            → the 6-digit OTP generated by the backend
 *
 * Required Supabase secrets:
 *   CHINGUISOFT_BASE_URL         — e.g. https://chinguisoft.com  (no trailing slash)
 *   CHINGUISOFT_VALIDATION_KEY   — goes in the URL path
 *   CHINGUISOFT_VALIDATION_TOKEN — goes in the Validation-token header
 */

// ─── Types ────────────────────────────────────────────────────────────────────

export interface ChinguisoftConfig {
  baseUrl:         string  // https://chinguisoft.com
  validationKey:   string  // URL path segment
  validationToken: string  // Validation-token header value
}

export interface SmsSendResult {
  ok:     boolean  // true when HTTP status is 2xx
  status: number   // raw HTTP status code
  body:   string   // response body trimmed to 500 chars — safe to log
}

// ─── Phone normalisation ──────────────────────────────────────────────────────

/**
 * Strips the +222 international prefix from a full Mauritanian phone number.
 * Returns the 8-digit local format expected by ChinguiSoft.
 *
 *   +22249141433 → 49141433
 *   +22236000000 → 36000000
 */
export function toLocalPhone(phone: string): string {
  return phone.replace(/^\+222/, '')
}

// ─── SMS sender ───────────────────────────────────────────────────────────────

/**
 * Sends a validation SMS via the ChinguiSoft API.
 *
 * @param phone  Full international number (+222XXXXXXXX). Normalised internally.
 * @param code   6-digit OTP code to embed in the message.
 * @param config Resolved ChinguiSoft secrets (never undefined at this point).
 * @param lang   SMS language. Defaults to "fr".
 */
export async function sendValidationSms(
  phone:  string,
  code:   string,
  config: ChinguisoftConfig,
  lang:   'fr' | 'ar' = 'fr',
): Promise<SmsSendResult> {
  const localPhone = toLocalPhone(phone)

  // URL: POST /api/sms/validation/{validation_key}
  // validation_key is a path segment — NOT a query param, NOT a header.
  const url = `${config.baseUrl}/api/sms/validation/${config.validationKey}`

  const res = await fetch(url, {
    method: 'POST',
    headers: {
      // Exact header name as documented — capital V, lowercase t
      'Validation-token': config.validationToken,
      'Content-Type':     'application/json',
    },
    body: JSON.stringify({
      phone: localPhone,  // 8-digit local format
      lang,               // "fr" or "ar"
      code,               // 6-digit OTP
    }),
  })

  // Read the body once to avoid "body already consumed" errors on retry logic
  const rawBody = await res.text().catch(() => '(unreadable body)')

  // Trim to 500 chars — keeps logs readable without exposing full provider HTML
  const body = rawBody.slice(0, 500)

  return { ok: res.ok, status: res.status, body }
}
